# Generated by Django 2.2.28 on 2023-01-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recept',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.AlterField(
            model_name='recept',
            name='cart_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recept',
            name='favorite_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
