# Generated by Django 2.2.28 on 2023-01-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0002_auto_20230105_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriete',
            name='recepet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriet', to='recept.Recept', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='ingredientreceptlink',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrrec', to='recept.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientreceptlink',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrrec', to='recept.Recept', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='cart_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='В корзине'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='favorite_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='В избранном'),
        ),
    ]
