# Generated by Django 2.2.28 on 2023-01-22 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0005_auto_20230121_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
    ]
