# Generated by Django 2.2.28 on 2023-01-29 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0006_auto_20230122_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientreceptlink',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='ingredientreceptlink',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
