# Generated by Django 2.2.28 on 2023-01-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0003_auto_20230108_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
