# Generated by Django 2.2.28 on 2023-01-21 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0004_auto_20230115_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recept',
            name='cart_count',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='favorite_count',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredientreceptlink',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='cooking_time',
            field=models.PositiveIntegerField(verbose_name='Время приготовления'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique ingredients'),
        ),
    ]
