# Generated by Django 2.2.28 on 2023-02-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0007_auto_20230129_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='recepet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='recept.Recept', verbose_name='Рецепт'),
        ),
    ]
